<a href="https://colab.research.google.com/github/yogeshshardulpro/250843116017_DAV/blob/main/pr_1_dav.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PEN : 250843116017

Practical 1 | Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON files using Pandas

Step 1 : Import Pandas

In [ ]:
# Import pandas library.
import pandas as pd

data = {
    "ID": [ 101, 102, 103, 104, 105, 106, 107],
    "Name": ["Rahul", "priya", "Amit", "Riya", "karan", "Krishna", "Harry"],
    "Age": [20, 21, 19, 20, 22, 24, 28],
    "City": ["surat", "Navsari", "Valsad", "Bharuch", "Surat", "Gandhinagar", "Ahmedabad"],
    "Marks":[85, 92, 78, 88, 81, 84, 90]
   }

Crate a dataframe

In [ ]:
# create a DataFrame from given data
# Display the DataFrame
df = pd.DataFrame(data)
df

    ID     Name  Age         City  Marks
0  101    Rahul   20        surat     85
1  102    priya   21      Navsari     92
2  103     Amit   19       Valsad     78
3  104     Riya   20      Bharuch     88
4  105    karan   22        Surat     81
5  106  Krishna   24  Gandhinagar     84
6  107    Harry   28    Ahmedabad     90

Step 4 : Save Data as CSV File

In [ ]:
# Export the DataFrame to a csv file
df.to_csv("data.csv", index=False)

print("csv file created")

csv file created

Step 5 : Save Data as Excel File

In [ ]:
# Export the DataFrame to an Excel file
df.to_excel("students_info.xlsx", index=False)
print("excel file created")

excel file created

Step 6 : Save Data as JSON file

In [ ]:
# Export the DataFrame to a JSON  file in records format
df.to_json("students.json", orient="records", indent=5)

print("json file created")

json file created

Read the CSV file

In [ ]:
# Read the CSV file into a DataFrame
df_csv = pd.read_csv("data.csv")
df_csv

    ID     Name  Age         City  Marks
0  101    Rahul   20        surat     85
1  102    priya   21      Navsari     92
2  103     Amit   19       Valsad     78
3  104     Riya   20      Bharuch     88
4  105    karan   22        Surat     81
5  106  Krishna   24  Gandhinagar     84
6  107    Harry   28    Ahmedabad     90

Read the Excel file

In [ ]:
# Read the Excel file into a Dataframe
df_excel = pd.read_excel("students_info.xlsx")
df_excel

    ID     Name  Age         City  Marks
0  101    Rahul   20        surat     85
1  102    priya   21      Navsari     92
2  103     Amit   19       Valsad     78
3  104     Riya   20      Bharuch     88
4  105    karan   22        Surat     81
5  106  Krishna   24  Gandhinagar     84
6  107    Harry   28    Ahmedabad     90

Read the JSON file

In [ ]:
# Read the exported JSON file back into a pandas Dataframe and display the result
df_json = pd.read_json("students.json")
df_json

    ID     Name  Age         City  Marks
0  101    Rahul   20        surat     85
1  102    priya   21      Navsari     92
2  103     Amit   19       Valsad     78
3  104     Riya   20      Bharuch     88
4  105    karan   22        Surat     81
5  106  Krishna   24  Gandhinagar     84
6  107    Harry   28    Ahmedabad     90

Display First Five Records

In [ ]:
# Display the first 5 rows of the CSV data
df_csv.head()

    ID   Name  Age     City  Marks
0  101  Rahul   20    surat     85
1  102  priya   21  Navsari     92
2  103   Amit   19   Valsad     78
3  104   Riya   20  Bharuch     88
4  105  karan   22    Surat     81

Display the Last Five Records

In [ ]:
# Display the last 5 rows of the CSV data
df_csv.tail()

    ID     Name  Age         City  Marks
2  103     Amit   19       Valsad     78
3  104     Riya   20      Bharuch     88
4  105    karan   22        Surat     81
5  106  Krishna   24  Gandhinagar     84
6  107    Harry   28    Ahmedabad     90

Step 12 : Display Dataset info

In [ ]:
# Display information about the Dataset, including columns, Data types, and non-null values
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

Display Statistical Summary

In [ ]:
# Display the statistical summary of numerical columns
df_csv.describe()

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  85.428571
std      2.160247   3.109126   4.961759
min    101.000000  19.000000  78.000000
25%    102.500000  20.000000  82.500000
50%    104.000000  21.000000  85.000000
75%    105.500000  23.000000  89.000000
max    107.000000  28.000000  92.000000

Step 14 : Display Dataset Shape

In [ ]:
# Display the number of rows and columns in the dataset
df_csv.shape

(7, 5)

Step 15 : Display Columns Names

In [ ]:
# Display the names of all columns in the dataset
df_csv = pd.read_csv("data.csv")
df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

Step 16 : Display Data Types

In [ ]:
# Display the data type of each columns
df_csv = pd.read_csv("data.csv")
df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

Step 17: Check for missing values

In [ ]:
# Check the number of missing values in each column
df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

Step 18 : Display a single column

In [ ]:
# Display the values from the Name column
df_csv["Name"]

0      Rahul
1      priya
2       Amit
3       Riya
4      karan
5    Krishna
6      Harry
Name: Name, dtype: object

Display Multiple columns

In [ ]:
# Filter students whose age is greater than 20
df_csv[["Name", "Age"]]

      Name  Age
0    Rahul   20
1    priya   21
2     Amit   19
3     Riya   20
4    karan   22
5  Krishna   24
6    Harry   28

Step 20 : Filter Records

In [ ]:
# Filter students whose marks are greater than 85
df_csv[df_csv["Marks"] > 85]

    ID   Name  Age       City  Marks
1  102  priya   21    Navsari     92
3  104   Riya   20    Bharuch     88
6  107  Harry   28  Ahmedabad     90

Step 21 : Calculate Average Marks

In [ ]:
# Calculate the average marks of all students
df_csv["Marks"].mean()

np.float64(85.42857142857143)

Step 22 : Sort Data

In [ ]:
# Sort the data by marks in descending order
df_csv.sort_values(by="Marks", ascending=False)

    ID     Name  Age         City  Marks
1  102    priya   21      Navsari     92
6  107    Harry   28    Ahmedabad     90
3  104     Riya   20      Bharuch     88
0  101    Rahul   20        surat     85
5  106  Krishna   24  Gandhinagar     84
4  105    karan   22        Surat     81
2  103     Amit   19       Valsad     78

Display DF

In [ ]:
# Print the complete Dataframe
print(df_csv)

    ID     Name  Age         City  Marks
0  101    Rahul   20        surat     85
1  102    priya   21      Navsari     92
2  103     Amit   19       Valsad     78
3  104     Riya   20      Bharuch     88
4  105    karan   22        Surat     81
5  106  Krishna   24  Gandhinagar     84
6  107    Harry   28    Ahmedabad     90