PEN : 250843116017

Practical_2 :Perform data inspection, cleaning, handling missing values, duplicate removal, and data transformation using Pandas.

step 1 : Import pandas as pd

In [29]:
# import pandas and create dataframe from data
import pandas as pd

data={
    "ID": [ 101, 102, 103, 104, 105, 106, 107,108],
    "Name": ["Rahul", "priya", "Amit", None,"Riya", "karan", "Jay", "soham"],
    "Age": [20, 21,None, 19, 20, 22, 24, 25],
    "City": ["surat", "Navsari", "Valsad", "Rajkot", "Surat", "Gandhinagar", "Ahmedabad",None],
    "Marks":[85, None, 78, 88, 81, 84, 90, 92]
}
ys = pd.DataFrame(data)
ys

    ID   Name   Age         City  Marks
0  101  Rahul  20.0        surat   85.0
1  102  priya  21.0      Navsari    NaN
2  103   Amit   NaN       Valsad   78.0
3  104   None  19.0       Rajkot   88.0
4  105   Riya  20.0        Surat   81.0
5  106  karan  22.0  Gandhinagar   84.0
6  107    Jay  24.0    Ahmedabad   90.0
7  108  soham  25.0         None   92.0

Step 3 : Inspect the Dataset

In [30]:
# display 5 rows of dataframe using head
ys.head()

    ID   Name   Age     City  Marks
0  101  Rahul  20.0    surat   85.0
1  102  priya  21.0  Navsari    NaN
2  103   Amit   NaN   Valsad   78.0
3  104   None  19.0   Rajkot   88.0
4  105   Riya  20.0    Surat   81.0

In [31]:
# Display the last five rows of dataset
ys.tail()

    ID   Name   Age         City  Marks
3  104   None  19.0       Rajkot   88.0
4  105   Riya  20.0        Surat   81.0
5  106  karan  22.0  Gandhinagar   84.0
6  107    Jay  24.0    Ahmedabad   90.0
7  108  soham  25.0         None   92.0

In [32]:
# Display  information about database.

ys.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      float64
 3   City    7 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

In [33]:
# Display statistical informtaion for numerical columns.
ys.describe()

              ID        Age      Marks
count    8.00000   7.000000   7.000000
mean   104.50000  21.571429  85.428571
std      2.44949   2.225395   4.961759
min    101.00000  19.000000  78.000000
25%    102.75000  20.000000  82.500000
50%    104.50000  21.000000  85.000000
75%    106.25000  23.000000  89.000000
max    108.00000  25.000000  92.000000

In [34]:
# Discribe the names of all columns from data.
ys.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

In [35]:
# Display the shape of a data.
ys.shape

(8, 5)

In [36]:
# display types of a each column of dataframe.
ys.dtypes

ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

Stpe 4 : Check Missing Values

In [37]:
# count the missing values from dataset.
ys.isnull().sum()

ID       0
Name     1
Age      1
City     1
Marks    1
dtype: int64

In [38]:
# Diaplay a boolean dataframe.
ys.isnull().sum().sum()

np.int64(4)

In [39]:
# Calculate number of missing values in the dataframe. mean() calculate the average marks. fillna() replaces missing values.
ys["Marks"] = ys["Marks"].fillna(ys["Marks"].mean())

ys

    ID   Name   Age         City      Marks
0  101  Rahul  20.0        surat  85.000000
1  102  priya  21.0      Navsari  85.428571
2  103   Amit   NaN       Valsad  78.000000
3  104   None  19.0       Rajkot  88.000000
4  105   Riya  20.0        Surat  81.000000
5  106  karan  22.0  Gandhinagar  84.000000
6  107    Jay  24.0    Ahmedabad  90.000000
7  108  soham  25.0         None  92.000000

Fill Missing Age

In [40]:
# Replace missing values in age column
# using the average age of all students.

ys["Age"] = ys["Age"].fillna(ys["Age"].mean()).astype(int)

ys

    ID   Name  Age         City      Marks
0  101  Rahul   20        surat  85.000000
1  102  priya   21      Navsari  85.428571
2  103   Amit   21       Valsad  78.000000
3  104   None   19       Rajkot  88.000000
4  105   Riya   20        Surat  81.000000
5  106  karan   22  Gandhinagar  84.000000
6  107    Jay   24    Ahmedabad  90.000000
7  108  soham   25         None  92.000000

Fill Missing Name

In [41]:
# Replace missing values in the age column
# using the average age of all students.

ys["Name"] = ys["Name"].fillna("unknown")

ys

    ID     Name  Age         City      Marks
0  101    Rahul   20        surat  85.000000
1  102    priya   21      Navsari  85.428571
2  103     Amit   21       Valsad  78.000000
3  104  unknown   19       Rajkot  88.000000
4  105     Riya   20        Surat  81.000000
5  106    karan   22  Gandhinagar  84.000000
6  107      Jay   24    Ahmedabad  90.000000
7  108    soham   25         None  92.000000

Step 6 : Remove Dupliucate Records

In [42]:
# detect duplicate records from dataset.

ys.duplicated()

ys

    ID     Name  Age         City      Marks
0  101    Rahul   20        surat  85.000000
1  102    priya   21      Navsari  85.428571
2  103     Amit   21       Valsad  78.000000
3  104  unknown   19       Rajkot  88.000000
4  105     Riya   20        Surat  81.000000
5  106    karan   22  Gandhinagar  84.000000
6  107      Jay   24    Ahmedabad  90.000000
7  108    soham   25         None  92.000000

Detect Duplicate rows

In [43]:
#  count duplicate rows.
ys.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [44]:
ys.duplicated().sum()

np.int64(0)

Step 8 : Rename a column

In [45]:
#  Rename the column "Marks" to "Score". inplace True permanently upadates the Dataframe
ys.rename(columns={"Marks":"score"}, inplace=True)

ys

    ID     Name  Age         City      score
0  101    Rahul   20        surat  85.000000
1  102    priya   21      Navsari  85.428571
2  103     Amit   21       Valsad  78.000000
3  104  unknown   19       Rajkot  88.000000
4  105     Riya   20        Surat  81.000000
5  106    karan   22  Gandhinagar  84.000000
6  107      Jay   24    Ahmedabad  90.000000
7  108    soham   25         None  92.000000

Step 9 : Change Data Type

In [52]:
# convert age column from float value to integer.
ys['score'] = ys['score'].astype(int)
ys.dtypes

ID        int64
Name     object
Age       int64
City     object
score     int64
dtype: object

Step 10 : Add final score column by adding 5 marks

In [53]:
# create a new column and add 5 marks to the new column"score"
ys["final_score"] = ys["score"] + 5
ys

    ID     Name  Age         City  score  final_score
0  101    Rahul   20        surat     85           90
1  102    priya   21      Navsari     85           90
2  103     Amit   21       Valsad     78           83
3  104  unknown   19       Rajkot     88           93
4  105     Riya   20        Surat     81           86
5  106    karan   22  Gandhinagar     84           89
6  107      Jay   24    Ahmedabad     90           95
7  108    soham   25         None     92           97

Step 11 : convert text to uppercase

In [54]:
# convert a name from case to uppercase.
ys["Name"]=ys["Name"].str.upper()
ys

    ID     Name  Age         City  score  final_score
0  101    RAHUL   20        surat     85           90
1  102    PRIYA   21      Navsari     85           90
2  103     AMIT   21       Valsad     78           83
3  104  UNKNOWN   19       Rajkot     88           93
4  105     RIYA   20        Surat     81           86
5  106    KARAN   22  Gandhinagar     84           89
6  107      JAY   24    Ahmedabad     90           95
7  108    SOHAM   25         None     92           97

Step 12 : Convert text to lowercase

In [55]:
# Convert city from case to lowercase
ys["City"] = ys["City"].str.lower()
ys

    ID     Name  Age         City  score  final_score
0  101    RAHUL   20        surat     85           90
1  102    PRIYA   21      navsari     85           90
2  103     AMIT   21       valsad     78           83
3  104  UNKNOWN   19       rajkot     88           93
4  105     RIYA   20        surat     81           86
5  106    KARAN   22  gandhinagar     84           89
6  107      JAY   24    ahmedabad     90           95
7  108    SOHAM   25         None     92           97

Step 13 : Remove Extra Space

In [56]:
# Remove extra space
ys["City"] = ys["City"].str.strip()
ys

    ID     Name  Age         City  score  final_score
0  101    RAHUL   20        surat     85           90
1  102    PRIYA   21      navsari     85           90
2  103     AMIT   21       valsad     78           83
3  104  UNKNOWN   19       rajkot     88           93
4  105     RIYA   20        surat     81           86
5  106    KARAN   22  gandhinagar     84           89
6  107      JAY   24    ahmedabad     90           95
7  108    SOHAM   25         None     92           97

Step 14 : Sort the dataset

In [57]:
# Based on "Final_Score"sort a data.
ys.sort_values(by="final_score", ascending=False)

    ID     Name  Age         City  score  final_score
7  108    SOHAM   25         None     92           97
6  107      JAY   24    ahmedabad     90           95
3  104  UNKNOWN   19       rajkot     88           93
0  101    RAHUL   20        surat     85           90
1  102    PRIYA   21      navsari     85           90
5  106    KARAN   22  gandhinagar     84           89
4  105     RIYA   20        surat     81           86
2  103     AMIT   21       valsad     78           83

Step 15 : Save the cleaned dataset

In [58]:
# Save the clean dataset
ys.to_csv("cleaned_student.CSV",index=False)
print("Dataset create successfuly")

Dataset create successfuly